name: Deploy to Firebase

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Move into subdirectory (optional)
      - name: Move to vite-frontend
        working-directory: ./vite-frontend
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la

      # 3. Set up Node
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4. Install dependencies
      - name: Install
        working-directory: ./vite-frontend
        run: npm install
        
      # Install Firebase CLI
      - name: Install Firebase CLI
        working-directory: ./vite-frontend
        run: npm install -g firebase-tools

      # 5. Build your project (optional if you have a build step)
      - name: Build
        working-directory: ./vite-frontend
        run: npm run build

      # 6. Deploy to Firebase
      - name: Deploy to Firebase
        working-directory: ./vite-frontend
        run: npx firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
